# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/umt-fyp',
                'doc_host': 'https://moneebullah25.github.io',
                'git_url': 'https://github.com/moneebullah25/umt-fyp',
                'lib_path': 'umt_fyp'},
  'syms': {'umt_fyp.core': {}}}
